-- DBO.BUSINESS_DATE 은행업무기준일로 새로 만들어야 함 (BANK_DATE)

---
  DROP TABLE IF EXISTS #TMP	
  DECLARE @START_DATE DATETIME, @END_DATE DATETIME, @CUR_DATE DATETIME

  SET @START_DATE = '2018-01-01'
  SET @END_DATE = '2018-12-31'
  SET @CUR_DATE = @START_DATE

  CREATE TABLE #TMP
  (WEEKDAY VARCHAR(10),
  DATE VARCHAR(10),
  day int,
  month varchar(10),
  year int,
  WORK VARCHAR(10),
  PAYDAY VARCHAR(10)
  --PAYDAY_CMS VARCHAR(10),
  --PAYDAY_CARD VARCHAR(10),
  )

  WHILE @CUR_DATE <= @END_DATE
  BEGIN
    INSERT INTO #TMP
    SELECT DATENAME(DW, @CUR_DATE), CONVERT(VARCHAR(10), @CUR_DATE, 126), datepart(day, @cur_date), datename(month, @cur_date), datepart(year, @cur_date),
        CASE WHEN EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE, 126) 
  			 FROM DBO.BUSINESS_DATE BD WHERE CONVERT(VARCHAR(10), @CUR_DATE, 126) = BD.DATE)
			 THEN 'WORKDAY'
	    END,
		CASE WHEN RIGHT(CONVERT(VARCHAR(10), @CUR_DATE, 126), 2) IN ('10', '27')
				  AND
				  EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE, 126) 
  				  FROM DBO.BUSINESS_DATE BD WHERE CONVERT(VARCHAR(10), @CUR_DATE, 126) = BD.DATE)
				  THEN CONVERT(VARCHAR(10), @CUR_DATE, 126)
			 WHEN RIGHT(CONVERT(VARCHAR(10), @CUR_DATE, 126), 2) IN ('10', '27')
			      THEN (SELECT MIN(DATE) FROM DBO.business_date WHERE DATE > @CUR_DATE)
		END
    SET @CUR_DATE = DATEADD(DD, 1, @CUR_DATE)
  END


  -------------------
  DROP TABLE IF EXISTS #TMP2
  SELECT AAA.WEEKDAY, AAA.DATE, AAA.year, AAA.month, AAA.day, AAA.WORK, BBB.PAYDAY
  INTO #TMP2
  FROM #TMP AAA LEFT JOIN #TMP BBB
  ON AAA.DATE = BBB.PAYDAY


  -------------------
  DROP TABLE IF EXISTS #PAYDAY
  SELECT PAYDAY, RANK() OVER (PARTITION BY LEFT(PAYDAY, 7) ORDER BY RIGHT(PAYDAY, 2) ASC) AS TURN
  INTO #PAYDAY
  FROM #TMP2 
  WHERE PAYDAY IS NOT NULL
  
   
----

SELECT * FROM #PAYDAY 


------

DROP TABLE IF EXISTS #TMP3	
  DECLARE @START_DATE2 DATETIME, @END_DATE2 DATETIME, @CUR_DATE2 DATETIME

  SET @START_DATE2 = '2018-04-01'    -- 원하는 기간 입력
  SET @END_DATE2 = '2018-04-30'		 -- 원하는 기간 입력
  SET @CUR_DATE2 = @START_DATE2

  CREATE TABLE #TMP3
  (WEEKDAY VARCHAR(10),
  DATE VARCHAR(10),
  PAYDAY_CMS VARCHAR(20),
  PAYDAY_CARD VARCHAR(20),
  MEMO VARCHAR(20)
  )

  WHILE @CUR_DATE2 <= @END_DATE2
  BEGIN
    INSERT INTO #TMP3
    SELECT DATENAME(DW, @CUR_DATE2), CONVERT(VARCHAR(10), @CUR_DATE2, 126), 
        CASE WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)))) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 27'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126))) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 27'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 27'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
			 THEN 'CMS: 10'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)))) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 10'
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126))) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 10'
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)) = #PAYDAY.PAYDAY)
			 THEN 'CMS: 10'
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
			 THEN 'CMS: 27'
			 ELSE 'CMS: 10'
		 END,
		 CASE 
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)) = #PAYDAY.PAYDAY)
			 THEN '신용카드: 27'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 1)
			 THEN '신용카드: 10'
						
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
				  AND EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
							  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)) = #PAYDAY.PAYDAY)
			 THEN '신용카드: 10'
			
			 WHEN @CUR_DATE2 < (SELECT MIN(PAYDAY) FROM #PAYDAY WHERE PAYDAY >= @CUR_DATE2 AND datename(month, @CUR_DATE2) = SUBSTRING(PAYDAY, 6, 2) AND TURN = 2)
			 THEN '신용카드: 27'
			 ELSE '신용카드: 10'
		END,
		CASE WHEN EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
						  FROM #PAYDAY WHERE DBO.FN_GetNextBusinessDate(CONVERT(VARCHAR(10), @CUR_DATE2, 126)) = #PAYDAY.PAYDAY AND DATENAME(DW, @CUR_DATE2) NOT IN ('토요일','일요일'))
			 THEN '결제정보전송'
			 WHEN EXISTS (SELECT CONVERT(VARCHAR(10), @CUR_DATE2, 126)
						  FROM #PAYDAY WHERE CONVERT(VARCHAR(10), @CUR_DATE2, 126) = #PAYDAY.PAYDAY)
			 THEN '실결제'
			 ELSE ''
		END
    SET @CUR_DATE2 = DATEADD(DD, 1, @CUR_DATE2)
  END

SELECT * FROM #TMP3



/*
DAY가 NEXT_PAYDAY - 3 BUSINESSDAY 보다 작으면 10, 
DAY <= 25 이고,
DAY >= 26 이면 10 / 10

SELECT DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(getdate())))

*/

/*
SELECT DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(getdate())))  --오늘+3 업무일
SELECT DBO.FN_GetNextBusinessDate(DBO.FN_GetNextBusinessDate(getdate()))  --오늘+2 업무일
SELECT DBO.FN_GetNextBusinessDate(getdate())  --오늘+1 업무일


CMS
첫결제일 전이고 오늘+3업무일이 결제일이면 27 
첫결제일 전이고 오늘+2업무일이 결제일이면 27
첫결제일 전이고 오늘+1업무일이 결제일이면 27
첫결제일 전이고 해당 없으면 10

첫결제일 후 재결제일 전이고 오늘+3업무일이 결제일이면 10
첫결제일 후 재결제일 전이고 이하고 오늘+2업무일이 결제일이면 10
첫결제일 후 재결제일 전이고 오늘+업무일이 결제일이면 10
첫결제일 후 재결제일 전이고 해당 없으면 27
*/
